### ISSUE TITLE
Failed to parse source map runtime

### ISSUE THREAD

**Issue by lwazevedo** [Aakash1103Jha/thedevdesigner-react-lib#2]
Hi, 

I installed your package in my project to test it and when I run npm start, I get this warning:

Failed to parse source map from '/my_director/node_modules/thedevdesigner-react-lib/src/components/Button/Button.tsx' file: Error: ENOENT: no such file or directory, open '/my_director/node_modules/thedevdesigner-react -lib/src/components/Button/Button.tsx'

WARNING in ./node_modules/thedevdesigner-react-lib/dist/esm/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/my_director/node_modules/thedevdesigner-react-lib/src/components/Button/Button.tsx' file: Error: ENOENT: no such file or directory, open '/my_director/node_modules/thedevdesigner-react -lib/src/components/Button/Button.tsx'
  @ ./src/App.tsx 7:0-50 50:35-41
  @ ./src/index.tsx 7:0-24 11:33-36

**Comment by Aakash1103Jha** [comment]
Hi @lwazevedo 
Thanks for bringing this to my attention. I was able to reproduce this issue on my end as well but this seems to be an issue with `create-react-app` v5. [More info here](https://github.com/facebook/create-react-app/discussions/11767).

I have my eyes on the above mentioned PR, but in the mean time, you can add a `GENERATE_SOURCEMAP = false` flag in your start script to get around this issue.

![package json-2022-02-26-16-23-36](https://user-images.githubusercontent.com/52240895/155840558-e486d766-1659-45f9-941d-86c691f9ad14.png)


Also, this issue will not case any performance related problems.
